version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Senha123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - pessoa-network

networks:
  pessoa-network:
    driver: bridge